output.elasticsearch:
  enabled: true
  hosts: ["elasticsearch:9200"]
  index: packetbeat
setup.kibana:
  enabled: true
  host: "kibana:5601"

setup.template.name: "packetbeat"
setup.template.pattern: "packetbeat-*"

setup.dashboards:
  enabled: true

packetbeat.procs.enabled: true
packetbeat.interfaces:
  buffer_size_mb: 100
  type: af_packet
  snaplen: 1514
  device: any
packetbeat.flows:
  timeout: 30s
  period: 10s
packetbeat.protocols:
- type: icmp
  enabled: true

- type: dhcpv4
  ports: [67, 68]
  enabled: true

- type: dns
  ports: [53]
  enabled: true

- type: http
  ports: [80, 8080, 8000, 5000, 8002]
  enabled: true

- type: mysql
  ports: [3306,3307]
  enabled: true